#!/bin/bash

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 "$PROJECT/$FILE"
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES \"$PROJECT/$FILE\""
done

if [ -f "$PROJECT/phpcs.ruleset.xml" ]
then
    RULESET="$PROJECT/phpcs.ruleset.xml"
elif [ -f "$PROJECT/phpcs.xml.dist" ]
then
    RULESET="$PROJECT/phpcs.xml.dist"
else
    RULESET="WordPress"
fi

echo "Checking Code Standard Compliance, using $RULESET as ruleset standard..."
for FILE in $SFILES
do
    ./vendor/bin/phpcs --standard="$RULESET" --colors --encoding=utf-8 -n -p "$PROJECT/$FILE"
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        echo "Run"
        echo "  ./vendor/bin/phpcbf --standard=\"$RULESET\" $FILES"
        echo "for automatic fix or fix it manually."
        exit 1
    fi
done

exit $?
